package lumber

import (
	"regexp"

	"github.com/sirupsen/logrus"
)

// HACK: this class remove unnecessary spaces generated by logrus.TextFormatter,
//       which always allocates at least 44 characters for message area.
//
//       https://github.com/sirupsen/logrus/blob/v1.4.2/text_formatter.go#L246-L252

type TextFormatter struct {
	*logrus.TextFormatter
}

func (f *TextFormatter) Format(entry *logrus.Entry) ([]byte, error) {
	original, err := f.TextFormatter.Format(entry)
	if err != nil {
		return nil, err
	}
	return f.compact(original)
}

func (f *TextFormatter) compact(data []byte) ([]byte, error) {
	result := regexp.MustCompile(`\s{2,}`).ReplaceAll(data, []byte{' '})
	return result, nil
}
